title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-14
owner: ucsb-cs156-s25
repo_name: team02-s25-14
pull_requests: [{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"end-to-end-Help-Requests","number":137,"title":"End to end help requests","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/137"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"sm-commits-integration-tests","number":136,"title":"sm - add integration tests for Help Requests Controller endpoints","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/136"}]
