title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-14
owner: ucsb-cs156-s25
repo_name: team02-s25-14
pull_requests: [{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-createPage","number":74,"title":"Create Page for RecommendationRequest plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/74"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"sm-commit-fixtures","number":73,"title":"create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/73"},{"author":{"id":"U_kgDOBZUlcw","is_bot":false,"login":"andrewzhang0708","name":"Andrew Zhang"},"headRefName":"az-backend-curl","number":72,"title":"az-created backend crud organizations","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/72"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"copy-backend-crud-menuitems","number":71,"title":"Copy Backend CRUD files for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/71"}]
