title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-14
owner: ucsb-cs156-s25
repo_name: team02-s25-14
pull_requests: [{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"3rd-helprequestformbranch","number":88,"title":"3rd helprequestformbranch","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/88"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"2nd-sm-helprequestform","number":86,"title":"Seeing if 2nd branch work for sm helprequestform","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/86"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-testingerrors","number":85,"title":"Fixing Errors from Pull Request #77 ","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/85"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-team03-2","number":83,"title":"End 2 End Tests for RecommendationRequestTable","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/83"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-team03","number":82,"title":"Creating two Integration Tests for RecommendationRequest Table - Team03","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/82"}]
