title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-14
owner: ucsb-cs156-s25
repo_name: team02-s25-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1NDY4MjU1","is_bot":false,"login":"karenlyuan","name":"Karen Yuan"},"headRefName":"karenlyuan-create-articles-page","number":126,"title":"karenlyuan - fixed articles pages after code was accidentally deleted from merge conflicts","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/126"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"rc-menuitems-integration-tests","number":125,"title":"Rc menuitems integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/125"},{"author":{"id":"U_kgDOBZUlcw","is_bot":false,"login":"andrewzhang0708","name":"Andrew Zhang"},"headRefName":"az-organizations-pages","number":122,"title":"Finished Working on Pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/122"}]
