title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-14
owner: ucsb-cs156-s25
repo_name: team02-s25-14
pull_requests: [{"author":{"id":"U_kgDOB3Ewuw","is_bot":false,"login":"shruthiunnithan","name":"Shruthi Santhosh Unnithan"},"headRefName":"shruthiunnithan-menuitemreview-index","number":108,"title":"Shruthiunnithan menuitemreview index","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/108"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"sm-copy-placeholders-helprequest","number":107,"title":"Sm copy placeholders helprequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/107"},{"author":{"id":"U_kgDOBZUlcw","is_bot":false,"login":"andrewzhang0708","name":"Andrew Zhang"},"headRefName":"az-organization-table","number":106,"title":"az-created table","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/106"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"HelpRequestTable","number":96,"title":"Help request table","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/96"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"2nd-sm-helprequestform","number":86,"title":"Seeing if 2nd branch work for sm helprequestform","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/86"}]
