title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-14
owner: ucsb-cs156-s25
repo_name: team02-s25-14
pull_requests: [{"author":{"id":"U_kgDOBZUlcw","is_bot":false,"login":"andrewzhang0708","name":"Andrew Zhang"},"headRefName":"az-organization-fixture","number":91,"title":"Added organization fixture","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/91"},{"author":{"id":"MDQ6VXNlcjY1NDY4MjU1","is_bot":false,"login":"karenlyuan","name":"Karen Yuan"},"headRefName":"karenlyuan-articles-form","number":90,"title":"karenlyuan - add form for Articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/90"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"rc-menuitemstable","number":89,"title":"Rc menuitemstable","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/89"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"rc-menuitemsform","number":87,"title":"rc - create form component plus tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/87"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"2nd-sm-helprequestform","number":86,"title":"Seeing if 2nd branch work for sm helprequestform","url":"https://github.com/ucsb-cs156-s25/team02-s25-14/pull/86"}]
